//! Thin, safe wrapper around the Accessibility C API.
//!
//! Everything returns `Result`; AX errors are expected in normal operation
//! (app is quitting, element already gone, app not responding) and must
//! never cause a panic.

use std::ffi::c_void;
use std::ptr::NonNull;

use objc2_application_services::{AXError, AXObserver, AXObserverCallback, AXUIElement};
use objc2_core_foundation::{
    CFArray, CFRetained, CFRunLoop, CFRunLoopSource, CFString, CFType, kCFRunLoopDefaultMode,
};

// These string constants are `#define`s to CFSTR literals in the C headers
// and are not generated by header-translator; the values are stable public
// API.
pub const NOTIF_WINDOW_CREATED: &str = "AXWindowCreated";
pub const NOTIF_ELEMENT_DESTROYED: &str = "AXUIElementDestroyed";
pub const ATTR_WINDOWS: &str = "AXWindows";
pub const ATTR_SUBROLE: &str = "AXSubrole";
pub const ATTR_MINIMIZED: &str = "AXMinimized";
pub const SUBROLE_STANDARD_WINDOW: &str = "AXStandardWindow";
/// Private Electron/Chromium attribute that enables their AX tree.
pub const ATTR_MANUAL_ACCESSIBILITY: &str = "AXManualAccessibility";

pub type AxResult<T> = Result<T, AXError>;

fn check(err: AXError) -> AxResult<()> {
    if err == AXError::Success {
        Ok(())
    } else {
        Err(err)
    }
}

pub fn application_element(pid: libc::pid_t) -> CFRetained<AXUIElement> {
    let element = unsafe { AXUIElement::new_application(pid) };
    // Keep individual calls bounded. Recounts run on a worker, while observer
    // setup still happens on the main thread.
    let _ = unsafe { element.set_messaging_timeout(0.25) };
    element
}

/// Copies an attribute value; the caller owns the result.
pub fn copy_attribute(element: &AXUIElement, name: &str) -> AxResult<CFRetained<CFType>> {
    let attr = CFString::from_str(name);
    let mut out: *const CFType = std::ptr::null();
    let err = unsafe {
        element.copy_attribute_value(&attr, NonNull::new(&mut out).expect("stack pointer"))
    };
    check(err)?;
    let ptr = NonNull::new(out.cast_mut()).ok_or(AXError::Failure)?;
    Ok(unsafe { CFRetained::from_raw(ptr) })
}

/// All window elements of the app (unfiltered).
pub fn windows(app_element: &AXUIElement) -> AxResult<Vec<CFRetained<AXUIElement>>> {
    let value = copy_attribute(app_element, ATTR_WINDOWS)?;
    let array = value.downcast::<CFArray>().map_err(|_| AXError::Failure)?;
    let mut result = Vec::new();
    // The AX API guarantees the element type is AXUIElement.
    for i in 0..array.count() {
        let ptr = unsafe { array.value_at_index(i) };
        if let Some(ptr) = NonNull::new(ptr.cast_mut()) {
            result.push(unsafe { CFRetained::retain(ptr.cast::<AXUIElement>()) });
        }
    }
    Ok(result)
}

/// Subrole of a window, e.g. "AXStandardWindow".
pub fn subrole(window: &AXUIElement) -> AxResult<String> {
    let value = copy_attribute(window, ATTR_SUBROLE)?;
    let s = value.downcast::<CFString>().map_err(|_| AXError::Failure)?;
    Ok(s.to_string())
}

/// Whether the window is minimized to the Dock. Read errors count as "not
/// minimized" — the callers in counter.rs then keep probing the window's
/// visibility instead of trusting this one attribute.
pub fn is_minimized(window: &AXUIElement) -> bool {
    copy_attribute(window, ATTR_MINIMIZED).is_ok_and(|value| {
        value
            .downcast::<objc2_core_foundation::CFBoolean>()
            .is_ok_and(|boolean| boolean.as_bool())
    })
}

// Private but long-stable bridge from an AX window element to its
// CGWindowID (used by every tiling window manager for the same purpose).
unsafe extern "C" {
    fn _AXUIElementGetWindow(element: &AXUIElement, out: *mut u32) -> AXError;
}

/// CGWindowID of the window element, `None` if the bridge fails.
pub fn window_id(window: &AXUIElement) -> Option<u32> {
    let mut out: u32 = 0;
    let err = unsafe { _AXUIElementGetWindow(window, &mut out) };
    (err == AXError::Success && out != 0).then_some(out)
}

/// Sets the Electron/Chromium attribute that lazily enables their AX tree.
/// Best effort — errors are ignored (non-Electron apps don't know it).
pub fn nudge_electron(app_element: &AXUIElement) {
    let attr = CFString::from_str(ATTR_MANUAL_ACCESSIBILITY);
    let value = objc2_core_foundation::CFBoolean::new(true);
    let _ = unsafe { app_element.set_attribute_value(&attr, value.as_ref()) };
}

/// AXObserver plus its run-loop source; the source is invalidated on drop,
/// after which no callback can fire anymore.
pub struct Observer {
    observer: CFRetained<AXObserver>,
    source: CFRetained<CFRunLoopSource>,
}

impl Observer {
    pub fn new(pid: libc::pid_t, callback: AXObserverCallback) -> AxResult<Observer> {
        let mut out: *mut AXObserver = std::ptr::null_mut();
        let err = unsafe {
            AXObserver::create(
                pid,
                callback,
                NonNull::new(&mut out).expect("stack pointer"),
            )
        };
        check(err)?;
        let observer = unsafe { CFRetained::from_raw(NonNull::new(out).ok_or(AXError::Failure)?) };
        let source = unsafe { observer.run_loop_source() };
        let run_loop = CFRunLoop::main().ok_or(AXError::Failure)?;
        run_loop.add_source(Some(&source), unsafe { kCFRunLoopDefaultMode });
        Ok(Observer { observer, source })
    }

    pub fn add_notification(
        &self,
        element: &AXUIElement,
        notification: &str,
        refcon: *mut c_void,
    ) -> AxResult<()> {
        let name = CFString::from_str(notification);
        check(unsafe { self.observer.add_notification(element, &name, refcon) })
    }

    pub fn remove_notification(&self, element: &AXUIElement, notification: &str) {
        let name = CFString::from_str(notification);
        // Deregistration errors don't matter (element/app often already gone).
        let _ = unsafe { self.observer.remove_notification(element, &name) };
    }
}

impl Drop for Observer {
    fn drop(&mut self) {
        self.source.invalidate();
    }
}
